### ISSUE TITLE
作者您好，感谢您开源这么好的项目.问下咱们是否支持自己训练数字人.是否开源了训练代码

### ISSUE THREAD

**Issue by yulj21** [GuijiAI/duix.ai#2]

**Comment by GuijiIntelligence** [comment]
谢谢关注，暂时没有开源训练部分的计划。

**Comment by yaleimeng** [comment]
好家伙，这个SDK开源主要也是为了让客户定制形象来赚钱。如果把这个开源了他们公司岂不是关门了？ 如果你是老总你能批准吗：）

**Comment by yulj21** [comment]
那这是开源了个啥，给你一个盒子，里面东西不给

**Comment by yaleimeng** [comment]
公开了一批部署、调用它模型推理的API，也就是SDK。
简单玩玩那几个公版模型也够你体验了。给几个玩玩他也没什么损失，主要是吸引潜在用户。
你要换形象，交钱、定制。新的模型换上就能用。代码改动小。

**Comment by yulj21** [comment]
这不是开源，这纯粹打广告

---- 回复的原邮件 ----
| 发件人 | Yalei ***@***.***> |
| 发送日期 | 2024年06月22日 14:43 |
| 收件人 | ***@***.***> |
| 抄送人 | yulj21 ***@***.***>,
Author ***@***.***> |
| 主题 | Re: [GuijiAI/duix.ai] 作者您好，感谢您开源这么好的项目.问下咱们是否支持自己训练数字人.是否开源了训练代码 (Issue #2) |

公开了一批部署、调用它模型推理的API，也就是SDK。
简单玩玩那几个公版模型也够你体验了。给几个玩玩他也没什么损失，主要是吸引潜在用户。
你要换形象，交钱、定制。新的模型换上就能用。代码改动小。
