### ISSUE TITLE
IOS端，声音很小的问题

### ISSUE THREAD

**Issue by yapianwan** [GuijiAI/duix.ai#30]
同一个音频文件，放到工程目录下打包编译后，播放，音量正常。如果通过接口下载保存到缓存目录里面，再播放，音量很小，不知道是什么原因？

**Comment by njjnjjnjj** [comment]
注意观察以下声音是从 听筒播放的还是通过 扬声器播放，ios不知道，安卓有这个问题，代码里面固定使用通话模式，在这个模式下，生硬默认从听筒播放
