### ISSUE TITLE
iOS端打不开

### ISSUE THREAD

**Issue by rango123456** [GuijiAI/duix.ai#6]
ld:framework not found AFNetworking

**Comment by songwei01** [comment]
请用GJLocalDigitalDemo.xcworkspace文件打开项目

**Comment by rango123456** [comment]
用的就是xcworkspace打开的项目 报错找不到 AFNetworking

**Comment by songwei01** [comment]
> 用的就是xcworkspace打开的项目 报错找不到 AFNetworking
使用cocospod 安装的AFNetworking 怎么会找不到呢，检查项目pod文件下有没有AFNetworking
![2](https://github.com/GuijiAI/duix.ai/assets/4424832/baec3aae-b351-42c2-b113-2b9d5b9db4ec)

**Comment by rango123456** [comment]
![782eb20af76df35cdd12466f0](https://github.com/GuijiAI/duix.ai/assets/10952415/63263731-9c35-4ee3-b392-7b1cbd1fb1a2)
有啊 但是就是报错啊

**Comment by rango123456** [comment]
你自己下载试试

**Comment by songwei01** [comment]
自己下载是ok的，你检查下你的配置，不行pod install 自己重新用pod 安装下AFNetworking

**Comment by songwei01** [comment]
这个是真机运行的，有没有连真机

**Comment by rango123456** [comment]
连了真机  还是那不行 pod install 还是不行，麻烦能把可以运行的发我邮箱吗？renshaolei0725@163.com 谢谢

**Comment by songwei01** [comment]
> 连了真机 还是那不行 pod install 还是不行，麻烦能把可以运行的发我邮箱吗？[renshaolei0725@163.com](mailto:renshaolei0725@163.com) 谢谢

已经是开源代码，AF是网络通用库，看下你的xcode配置的路径，或者去掉pod，直接把AF代码加入项目

**Comment by songwei01** [comment]
你用的Xcode14.1 请使用最新的xcode版本

**Comment by rango123456** [comment]
使用最新Xcode 版本没问题了
